Repository GSG-G13/Balanty, pull requests merged in 2023-06, with the labels that each got.

#2 File structior
  .env.example
  .eslintignore
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  __tests__/test.test.ts
  client/.eslintignore
  client/.eslintrc.json
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/components/index.ts
  client/src/config.ts
  client/src/helpers/.gitkeep
  client/src/index.css
  client/src/layouts/.gitkeep
  client/src/main.tsx
  client/src/routes/.gitkeep
  client/src/services/.gitkeep
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  package-lock.json
  package.json
  server/app.ts
  server/config/environment.ts
  server/controllers/index.ts
  server/database/config/.gitkeep
  server/database/config/index.ts
  server/index.ts
  server/interfaces/index.ts
  server/middleware/index.ts
  server/models/index.ts
  server/package-lock.json
  server/routes/router.ts
  server/services/index.ts
  server/validations/index.ts
  tsconfig.json
Labels: waiting-review

#4 3 compleate file structure config
  .eslintrc.json
  .github/ISSUE_TEMPLATE/backend-feature.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/frontend-component-template.md
  .github/workflows/index.yml
  .husky/pre-commit
  __tests__/index.test.ts
  __tests__/test.test.ts
  package-lock.json
  package.json
Labels: done

#9 Fix build
  .gitattributes
  client/.eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/components/index.ts
  client/src/config.ts
  client/src/main.tsx
  client/tsconfig.json
  package-lock.json
  package.json
  server/config/environment.ts
  server/controllers/index.ts
  server/database/config/index.ts
  server/interfaces/index.ts
  server/middleware/index.ts
  server/models/index.ts
  server/services/index.ts
  server/validations/index.ts
  tsconfig.json
Labels: awaiting-review

#11 Create error wrapper and custom error
  client/package.json
  server/utils/errorHandler/CustomError.ts
  server/utils/errorHandler/errorWrapper.ts
Labels: done

#14 5 create connection database
  .env.example
  package-lock.json
  package.json
  server/config/environment.ts
  server/config/index.ts
  server/database/config/.gitkeep
  server/database/config/conection.ts
  server/index.ts
  server/utils/errorHandler/errorWrapper.ts
Labels: done

#13 create: Error Handler
  package-lock.json
  package.json
  server/middleware/errorMiddleware.ts
  server/package-lock.json
  server/utils/errorHandler/CustomError.ts
  server/utils/errorHandler/errorWrapper.ts
  server/utils/errorHandler/index.ts
  server/utils/index.ts
Labels: awaiting-review

#19 Handle readme file
  README.md
Labels: done

#21 init users stadium models
  .husky/commit-msg
  commitlint.config.js
  package-lock.json
  package.json
  server/config/environment.ts
  server/database/config/conection.ts
  server/database/config/index.ts
  server/database/index.ts
  server/index.ts
  server/models/Player.ts
  server/models/Stadium.ts
  server/models/index.ts
  tsconfig.json
Labels: done

#22 create model review
  server/config/environment.ts
  server/database/config/connection.ts
  server/database/config/index.ts
  server/index.ts
  server/models/Review.ts
  server/models/index.ts
Labels: done

#23 17 create messages model
  server/models/index.ts
  server/models/messages.ts
Labels: done

#33 12 create matches comments models
  server/database/config/build.ts
  server/models/Match.ts
  server/models/index.ts
Labels: awaiting-review

#35 init rootlayout component
  client/.eslintrc.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/RootComponents/leftSideBar/LeftSideBar.tsx
  client/src/components/RootComponents/leftSideBar/SideBarLink.tsx
  client/src/components/RootComponents/leftSideBar/UserCart.tsx
  client/src/components/RootComponents/navBar/NavBar.tsx
  client/src/components/RootComponents/rightSideBar/MyMatches.tsx
  client/src/components/RootComponents/rightSideBar/RightSideBar.tsx
  client/src/components/RootComponents/rightSideBar/RightSideBarTitle.tsx
  client/src/components/RootComponents/rightSideBar/TeamName.tsx
  client/src/components/RootComponents/rightSideBar/WorldMatch.tsx
  client/src/components/index.ts
  client/src/components/styledRootComponent/LiftSideBarStyledComponent.tsx
  client/src/components/styledRootComponent/Nav.tsx
  client/src/components/styledRootComponent/RightSideBarStyldComponent.tsx
  client/src/components/styledRootComponent/SideComponents.tsx
  client/src/index.css
  client/src/layouts/.gitkeep
  client/src/layouts/RootLayout.tsx
  client/src/main.tsx
  client/src/themes/LightTheme.tsx
  client/src/themes/index.ts
  client/vite.config.ts
  package.json
Labels: done

#44 32 create models relations db build
  server/database/config/build.ts
  server/database/config/index.ts
  server/models/Gallery.ts
  server/models/Match.ts
  server/models/Message.ts
  server/models/Player.ts
  server/models/Review.ts
  server/models/Stadium.ts
  server/models/User.ts
  server/models/index.ts
Labels: awaiting-review

#42 build: create contact us component and make styled component
  client/src/assets/imgContact.svg
  client/src/assets/imgS.svg
  client/src/components/contact-us/ContactUs.styled.tsx
  client/src/components/contact-us/ContactUs.tsx
  client/src/components/index.ts
  package-lock.json
  package.json
Labels: done

#43 build: definition who we are and styled mui
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/Definition/Definition.styled.tsx
  client/src/components/Definition/Definition.tsx
  client/src/components/Definition/DefinitionSection.tsx
Labels: done

#45 build: create Features of Balanty
  client/package.json
  client/src/assets/feature.svg
  client/src/components/Features/FeatureSection.tsx
  client/src/components/Features/Features.styled.tsx
  client/src/components/Features/Features.tsx
Labels: done

#52 build: create calendar component
  client/package-lock.json
  client/package.json
  client/src/components/calender/Calender.tsx
  client/src/index.css
  package-lock.json
  package.json
  server/index.ts
Labels: awaiting-review

#41 25 create best stadiums section
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/best-stadiums/BestStadiums.styled.tsx
  client/src/components/best-stadiums/BestStadiums.tsx
  client/src/components/best-stadiums/Stadium.tsx
  client/src/components/index.ts
Labels: awaiting-review

#56 fix: delete duplicate folder
  server/dataBase/config/build.ts
  server/dataBase/config/connection.ts
  server/dataBase/config/index.ts
  server/dataBase/config/seeds.json
  server/dataBase/index.ts
  server/database/config/InsertData.ts
  server/database/config/build.ts
  server/database/config/insertData.ts
  server/index.ts
  server/models/Gallery.ts
  server/models/Match.ts
  server/models/Message.ts
  server/models/Player.ts
  server/models/Review.ts
  server/models/Stadium.ts
  server/models/User.ts
Labels: awaiting-review

#58 build: build hero section
  client/src/components/hero/Hero.tsx
  client/src/components/hero/HeroDescription.tsx
  client/src/components/hero/HeroSection.styled.tsx
  client/src/components/hero/HeroSection.tsx
Labels: done

#59 53 build create match router
  .eslintrc.json
  __tests__/index.test.ts
  jest.config.js
  package-lock.json
  package.json
  server/app.ts
  server/config/environment.ts
  server/controllers/index.ts
  server/controllers/matches.ts
  server/database/config/seeds.json
  server/database/index.ts
  server/interfaces/index.ts
  server/interfaces/matchInterfaces.ts
  server/models/Match.ts
  server/routes/matchesRouter.ts
  server/routes/router.ts
  server/services/index.ts
  server/services/matches.ts
  server/utils/errorHandler/errorWrapper.ts
  server/validations/index.ts
  server/validations/matchSchema.ts
Labels: done

#78 build: build get stadium matches Router
  __tests__/index.test.ts
  jest.config.js
  package-lock.json
  package.json
  server/controllers/index.ts
  server/controllers/stadiums.ts
  server/database/config/seeds.json
  server/routes/router.ts
  server/routes/staduimRouter.ts
  server/services/index.ts
  server/services/stadiums.ts
  tsconfig.json
Labels: awaiting-review

#82 refactor: checking for time on GET/stadiums/matches/StadiumId
  server/services/matches.ts
Labels: awaiting-review

#75 60 build creatematch component
  .vscode/settings.json
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/RootComponents/leftSideBar/LeftSideBar.tsx
  client/src/components/calender/Calender.tsx
  client/src/components/createMatchComponents/CreateMatchCalendar.tsx
  client/src/components/createMatchComponents/CreateMatchForm.tsx
  client/src/components/createMatchComponents/createMatchStyled.ts
  client/src/components/createMatchComponents/index.ts
  client/src/components/createMatchStyled/createMatchStyled.ts
  client/src/components/index.ts
  client/src/components/styledRootComponent/Nav.tsx
  client/src/components/styledRootComponent/SideComponents.tsx
  client/src/context/.gitkeep
  client/src/context/CreateMatch.tsx
  client/src/context/RootLayout.tsx
  client/src/context/index.ts
  client/src/fullcalendar-custom.css
  client/src/index.css
  client/src/interfaces/index.ts
  client/src/interfaces/matchInterface.ts
  client/src/layouts/RootLayout.tsx
  client/src/main.tsx
  client/src/pages/CreateMatch.tsx
  client/src/validation/MatchSchema.ts
  client/vite.config.ts
  package-lock.json
  package.json
  server/controllers/matches.ts
  server/database/config/seeds.json
Labels: awaiting-review

#69 31 footer
  client/src/components/footer/footer.styled.tsx
  client/src/components/footer/footer.tsx
  client/src/components/header/Header.tsx
  client/src/components/hero/HeroSection.styled.tsx
  client/src/pages/LandingPage.tsx
Labels: awaiting-review

#92 91 fix database relations
  __tests__/index.test.ts
  jest.config.js
  server/models/index.ts
Labels: awaiting-review

#86 build: create an image slider
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/RootComponents/leftSideBar/LeftSideBar.tsx
  client/src/components/RootComponents/rightSideBar/RightSideBar.tsx
  client/src/components/stadiumProfile/BioSection.tsx
  client/src/components/stadiumProfile/ImageSlider.tsx
  client/src/components/stadiumProfile/StadiumProfile.styled.tsx
  client/src/components/styledRootComponent/Nav.tsx
  client/src/components/styledRootComponent/SideComponents.tsx
  client/src/layouts/RootLayout.tsx
  client/src/pages/StadiumProfile.tsx
Labels: awaiting-review

#76 build: matches router and services
  __tests__/index.test.ts
  package.json
  server/controllers/index.ts
  server/controllers/matches.ts
  server/database/config/seeds.json
  server/index.ts
  server/interfaces/matchInterfaces.ts
  server/routes/matches.ts
  server/routes/router.ts
  server/services/index.ts
  server/services/matches.ts
Labels: awaiting-review

#93 Connect profile with backend
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/calender/Calender.tsx
  client/src/components/createMatchComponents/CreateMatchCalendar.tsx
  client/src/components/createMatchComponents/CreateMatchForm.tsx
  client/src/components/createMatchStyled/index.ts
  client/src/components/stadiumProfile/BioSection.tsx
  client/src/components/stadiumProfile/EditInput.tsx
  client/src/components/stadiumProfile/ImageSlider.tsx
  client/src/components/stadiumProfile/ProfileCalender.tsx
  client/src/components/stadiumProfile/StadiumProfile.styled.tsx
  client/src/components/stadiumProfile/index.ts
  client/src/components/styledRootComponent/Nav.tsx
  client/src/components/styledRootComponent/SideComponents.tsx
  client/src/components/styledRootComponent/index.ts
  client/src/interfaces/StadiumProfile.ts
  client/src/interfaces/index.ts
  client/src/pages/CreateMatch.tsx
  client/src/pages/StadiumProfile.tsx
Labels: awaiting-review

#90 89 GET stadium profile Router
  __tests__/index.test.ts
  server/controllers/index.ts
  server/controllers/stadiums.ts
  server/database/config/seeds.json
  server/models/Gallery.ts
  server/models/Match.ts
  server/models/Stadium.ts
  server/routes/matches.ts
  server/routes/staduimRouter.ts
  server/services/index.ts
  server/services/matches.ts
  server/services/stadiums.ts
Labels: done

#94 85 match room chat back
  server/controllers/index.ts
  server/controllers/matchChat.ts
  server/database/config/seeds.json
  server/interfaces/index.ts
  server/interfaces/matchInterfaces.ts
  server/models/Message.ts
  server/models/index.ts
  server/routes/matchChat.ts
  server/routes/router.ts
  server/services/index.ts
  server/services/matchChat.ts
  tsconfig.json
Labels: done

#101 fix: fix main conflict
  server/database/config/seeds.json
Labels: awaiting-review

#97 fix: fix tests error
  __tests__/index.test.ts
Labels: awaiting-review
